
import "./globals.css";
import { Roboto } from 'next/font/google'
import '../styles/AndiPage/main.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {
        <body className={roboto.className}>{ children}</body>}

    </html>
  );
}
